name: GCC for ARM build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GCC_VERSION: '9-2019-q4'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v2-beta
      with:
          node-version: 'v12'

    - name: Restore ARM GCC Cache
      id: arm-gcc-cache
      uses: actions/cache@v2
      with:
        path: arm-gcc
        key:  ${{ runner.os }}-arm-gcc-${{ env.GCC_VERSION }}
    - name: Install ARM GCC
      if: steps.arm-gcc-cache.outputs.cache-hit != 'true'
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: ${{ env.GCC_VERSION }}
        directory: arm-gcc
    - name: set PATH
      run: echo "::add-path::arm-gcc"

    - name: info
      run: ls .; ls arm-gcc; echo $PATH

    - name: make
      run: make TARGET=jm-v2.0 drop
