name: GCC for ARM build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v2-beta
      with:
          node-version: 'v12'
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: make
      run: make TARGET=jm-v2.0 drop

  
